name: sodium_example
description: Sample dart program for web and native

environment:
  sdk: ^3.11.0
resolution: workspace

dependencies:
  sodium: ^3.4.7

dev_dependencies:
  build_runner: ^2.10.5
  build_web_compilers: ^4.4.9
  lint: ^2.8.0

executables:
  native: main_native
