name: sodium_libs_example
description: Demonstrates how to use the sodium_libs plugin.
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ">3.41.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  sodium_libs: ^3.4.7

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.29.0
  tuple: ^2.0.2

flutter:
  uses-material-design: true
